### ISSUE TITLE
GitUtilsTest failure for signing commits

### ISSUE THREAD

**Issue by hdurix** [jhipster/jhipster-lite#147]
when running with a GPG key, we got this error message:

```
org.eclipse.jgit.api.errors.ServiceUnavailableException: Signing service is not available

	at org.eclipse.jgit.api.CommitCommand.sign(CommitCommand.java:290)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:247)
	at tech.jhipster.forge.generator.infrastructure.secondary.GitUtils.commit(GitUtils.java:39)
	at tech.jhipster.forge.generator.infrastructure.secondary.GitUtils.addAndCommit(GitUtils.java:27)
	at tech.jhipster.forge.generator.infrastructure.secondary.GitUtilsTest.shouldInitThenAddAndCommit(GitUtilsTest.java:38)
	...
```

maybe something with `setGpgConfig()`

**Comment by hdurix** [comment]
@pascalgrimaud it does not seem to be easy to fix this error. I tried to add a Signing service for `jgit` by adding the Maven dependency `org.eclipse.jgit.gpg.bc` but I've got a new error that I can't fix like "Failed to parse secret key file".

The other idea I've got: force the commit to not be signed, it's really easy to do and it might not be such a bad idea. As a developer, you want to sign your commit to show it is really you that produced the code. Here, I'not sure this is such important to prove this is someone in particular who generated the project using JHipster Lite :)

What do you think?

**Comment by pascalgrimaud** [comment]
> force the commit to not be signed, it's really easy to do and it might not be such a bad idea

Yes agree. Let's do this
