### ISSUE TITLE
PostgreSQL - Missing "config" package in configuration

### ISSUE THREAD

**Issue by fdelbrayelle** [jhipster/jhipster-lite#1819]
When generating a project with PostgreSQL and then launching `./mvnw spring-boot:run`, the following error occurs: 

```
Caused by: java.lang.ClassNotFoundException: Could not load requested class : fr.malt.commission.api.technical.infrastructure.secondary.postgresql.FixedPostgreSQL10Dialect
        at org.hibernate.boot.registry.classloading.internal.AggregatedClassLoader.findClass(AggregatedClassLoader.java:210)                                                                                       
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)                                                                                                                                         
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)                                                                                                                                         
        at java.base/java.lang.Class.forName0(Native Method)                                                                                                                                                       
        at java.base/java.lang.Class.forName(Class.java:467)                                                                                                                                                               at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:130)                                                                                  
        ... 44 common frames omitted                                                                                                                                                                               
```

Because of this line in `` :

```
spring.jpa.database-platform=fr.malt.commission.api.technical.infrastructure.secondary.postgresql.FixedPostgreSQL10Dialect
```

Fixed when adding "config" like this:

```
spring.jpa.database-platform=fr.malt.commission.api.technical.infrastructure.secondary.postgresql.config.FixedPostgreSQL10Dialect
```

**Comment by fdelbrayelle** [comment]
False positive, to be deleted ;) @pascalgrimaud
