### ISSUE TITLE
Error when starting JHLite with vite

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#2630]
Right now I have this error on main (even after cleaning maven and node local cache):

```
npm run dev

> jhlite@0.11.1-SNAPSHOT dev
> vite

failed to load config from .../jhipster-lite/vite.config.ts
error when starting dev server:
Error: Cannot find module 'node:path'
Require stack:
- .../jhipster-lite/node_modules/vite/dist/node-cjs/publicUtils.cjs
- .../jhipster-lite/node_modules/vite/index.cjs
- .../jhipster-lite/vite.config.ts
- .../jhipster-lite/node_modules/vite/dist/node/chunks/dep-561c5231.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (.../jhipster-lite/node_modules/vite/dist/node-cjs/publicUtils.cjs:5:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object._require.extensions..js (file:///.../jhipster-lite/node_modules/vite/dist/node/chunks/dep-561c5231.js:62742:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
```

No idea since when this is (I'm usually not using this feature)

**Comment by DamnClin** [comment]
cc @qmonmert if you have a quick on that one (I haven't searched at all :D)

**Comment by qmonmert** [comment]
@DamnClin I just tried and it works on my machine
Try this:
- rm -Rf node_modules
- rm package-lock.json
- npm i
- npm run dev

![image](https://user-images.githubusercontent.com/9989211/179398627-06799d2d-ff59-4886-bb8f-446360f470f5.png)

**Comment by DamnClin** [comment]
Same (even if I do get some updates in the package lock), some env infos: 

```
node --version
v14.17.5
```

```
npm --version
7.21.1
```

**Comment by qmonmert** [comment]
![image](https://user-images.githubusercontent.com/9989211/179398788-c54332a0-2717-48ad-873d-5e349541b4f5.png)

**Comment by DamnClin** [comment]
Ok, that's it :D I push the updated version of the package lock, thanks a lot

**Comment by qmonmert** [comment]
@DamnClin 👍

**Comment by pascalgrimaud** [comment]
Yes, Node 14 is broken for some dependencies, always try to use LTS, so node 16 here
