### ISSUE TITLE
Stackoverflow on main

### ISSUE THREAD

**Issue by antarus** [jhipster/jhipster-lite#2637]
I can't do verify the main branch

`
java.lang.StackOverflowError
	at tech.jhipster.lite.module.domain.JHipsterModuleFiles$JHipsterModuleFileBatchBuilder.template(JHipsterModuleFiles.java:79)
	at tech.jhipster.lite.module.domain.JHipsterModuleFiles$JHipsterModuleFileBatchBuilder.template(JHipsterModuleFiles.java:79)
	at tech.jhipster.lite.module.domain.JHipsterModuleFiles$JHipsterModuleFileBatchBuilder.template(JHipsterModuleFiles.java:79)
	at tech.jhipster.lite.module.domain.JHipsterModuleFiles$JHipsterModuleFileBatchBuilder.template(JHipsterModuleFiles.java:79)
	at tech.jhipster.lite.module.domain.JHipsterModuleFiles$JHipsterModuleFileBatchBuilder.template(JHipsterModuleFiles.java:79)`

**Comment by antarus** [comment]
https://github.com/jhipster/jhipster-lite/pull/2636

**Comment by DamnClin** [comment]
Yep, my bad, working on it, sorry for that, will be ok in a few minutes...

**Comment by pascalgrimaud** [comment]
Should be fixed

**Comment by antarus** [comment]
i confirm
