### ISSUE TITLE
Component test in Custom JHLite instances

### ISSUE THREAD

**Issue by DamnClin** [jhipster/jhipster-lite#3650]
In the current `custom-jhlite` version the documentation says to make a cucumber test for the module but it is not possible since there is no cucumber configured in this instance.

We can add a dependency to the `spring-boot-cucumber` module in `custom-jhlite` but that may cause some problem due to the duplicated spring-server configuration, need to make some tests and give some though to that

**Comment by DamnClin** [comment]
Ok, this is more challenging than I though, the main problem is the duplicated cucumber configuration: one from JHLite test dependency and one in the generated app to allow custom steps and tests. I need to take some time to fine an acceptable solution for that...

**Comment by pascalgrimaud** [comment]
Let's add a bounty for this

**Comment by DamnClin** [comment]
Claimed https://opencollective.com/generator-jhipster/expenses/99761

**Comment by pascalgrimaud** [comment]
@DamnClin : approved

**Comment by avdev4j** [comment]
hi @DamnClin 
I can reproduce the bug, here is the stacktrace. Is it because it has not been released yet?
```
Exception in thread "main" io.cucumber.core.exception.CompositeCucumberException: There were 2 exceptions. The details are in the stacktrace below.
	at io.cucumber.core.runtime.RethrowingThrowableCollector.getThrowable(RethrowingThrowableCollector.java:57)
	at io.cucumber.core.runtime.CucumberExecutionContext.getThrowable(CucumberExecutionContext.java:102)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:86)
	at io.cucumber.core.cli.Main.run(Main.java:87)
	at io.cucumber.core.cli.Main.main(Main.java:30)
	Suppressed: io.cucumber.core.backend.CucumberBackendException: Glue class class com.mycompany.myapp.cucumber.CucumberConfiguration and class tech.jhipster.lite.cucumber.CucumberConfiguration are both annotated with @CucumberContextConfiguration.
Please ensure only one class configures the spring context

By default Cucumber scans the entire classpath for context configuration.
You can restrict this by configuring the glue path.
Examples:
 - @CucumberOptions(glue = "com.example.application")
 - @ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.example.application") - src/test/resources/junit-platform.properties   cucumber.glue=com.example.application
 - src/test/resources/cucumber.properties         cucumber.glue=com.example.application

		at io.cucumber.spring.SpringFactory.checkOnlyOneClassHasCucumberContextConfiguration(SpringFactory.java:91)
		at io.cucumber.spring.SpringFactory.addClass(SpringFactory.java:64)
		at io.cucumber.java.JavaBackend.lambda$loadGlue$1(JavaBackend.java:42)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:67)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:58)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:33)
		at io.cucumber.java.JavaBackend.lambda$loadGlue$2(JavaBackend.java:41)
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
		at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174)
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
		at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
		at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
		at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
		at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
		at io.cucumber.java.JavaBackend.loadGlue(JavaBackend.java:41)
		at io.cucumber.core.runner.Runner.<init>(Runner.java:56)
		at io.cucumber.core.runtime.SingletonRunnerSupplier.createRunner(SingletonRunnerSupplier.java:44)
		at io.cucumber.core.runtime.SingletonRunnerSupplier.get(SingletonRunnerSupplier.java:35)
		at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:35)
		at io.cucumber.core.runtime.CucumberExecutionContext.getRunner(CucumberExecutionContext.java:133)
		at io.cucumber.core.runtime.CucumberExecutionContext.runBeforeAllHooks(CucumberExecutionContext.java:86)
		at io.cucumber.core.runtime.Runtime.lambda$run$0(Runtime.java:81)
		at io.cucumber.core.runtime.Runtime.execute(Runtime.java:94)
		at io.cucumber.core.runtime.Runtime.run(Runtime.java:80)
		... 2 more
	Suppressed: io.cucumber.core.backend.CucumberBackendException: Glue class class com.mycompany.myapp.cucumber.CucumberConfiguration and class tech.jhipster.lite.cucumber.CucumberConfiguration are both annotated with @CucumberContextConfiguration.
Please ensure only one class configures the spring context

By default Cucumber scans the entire classpath for context configuration.
You can restrict this by configuring the glue path.
Examples:
 - @CucumberOptions(glue = "com.example.application")
 - @ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.example.application") - src/test/resources/junit-platform.properties   cucumber.glue=com.example.application
 - src/test/resources/cucumber.properties         cucumber.glue=com.example.application

		at io.cucumber.spring.SpringFactory.checkOnlyOneClassHasCucumberContextConfiguration(SpringFactory.java:91)
		at io.cucumber.spring.SpringFactory.addClass(SpringFactory.java:64)
		at io.cucumber.java.JavaBackend.lambda$loadGlue$1(JavaBackend.java:42)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:67)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:58)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:33)
		at io.cucumber.java.JavaBackend.lambda$loadGlue$2(JavaBackend.java:41)
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
		at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174)
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
		at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
		at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
		at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
		at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
		at io.cucumber.java.JavaBackend.loadGlue(JavaBackend.java:41)
		at io.cucumber.core.runner.Runner.<init>(Runner.java:56)
		at io.cucumber.core.runtime.SingletonRunnerSupplier.createRunner(SingletonRunnerSupplier.java:44)
		at io.cucumber.core.runtime.SingletonRunnerSupplier.get(SingletonRunnerSupplier.java:35)
		at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:35)
		at io.cucumber.core.runtime.CucumberExecutionContext.getRunner(CucumberExecutionContext.java:133)
		at io.cucumber.core.runtime.CucumberExecutionContext.runAfterAllHooks(CucumberExecutionContext.java:91)
		at io.cucumber.core.runtime.Runtime.execute(Runtime.java:94)
		at io.cucumber.core.runtime.Runtime.run(Runtime.java:84)
		... 2 more

Before All/After All failed
io.cucumber.core.exception.CompositeCucumberException: There were 2 exceptions. The details are in the stacktrace below.
	at io.cucumber.core.runtime.RethrowingThrowableCollector.getThrowable(RethrowingThrowableCollector.java:57)
	at io.cucumber.core.runtime.CucumberExecutionContext.getThrowable(CucumberExecutionContext.java:102)
	at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:97)
	at io.cucumber.core.runtime.Runtime.execute(Runtime.java:94)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:85)
	at io.cucumber.core.cli.Main.run(Main.java:87)
	at io.cucumber.core.cli.Main.main(Main.java:30)
	Suppressed: io.cucumber.core.backend.CucumberBackendException: Glue class class com.mycompany.myapp.cucumber.CucumberConfiguration and class tech.jhipster.lite.cucumber.CucumberConfiguration are both annotated with @CucumberContextConfiguration.
Please ensure only one class configures the spring context

By default Cucumber scans the entire classpath for context configuration.
You can restrict this by configuring the glue path.
Examples:
 - @CucumberOptions(glue = "com.example.application")
 - @ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.example.application") - src/test/resources/junit-platform.properties   cucumber.glue=com.example.application
 - src/test/resources/cucumber.properties         cucumber.glue=com.example.application

		at io.cucumber.spring.SpringFactory.checkOnlyOneClassHasCucumberContextConfiguration(SpringFactory.java:91)
		at io.cucumber.spring.SpringFactory.addClass(SpringFactory.java:64)
		at io.cucumber.java.JavaBackend.lambda$loadGlue$1(JavaBackend.java:42)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:67)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:58)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:33)
		at io.cucumber.java.JavaBackend.lambda$loadGlue$2(JavaBackend.java:41)
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
		at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174)
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
		at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
		at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
		at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
		at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
		at io.cucumber.java.JavaBackend.loadGlue(JavaBackend.java:41)
		at io.cucumber.core.runner.Runner.<init>(Runner.java:56)
		at io.cucumber.core.runtime.SingletonRunnerSupplier.createRunner(SingletonRunnerSupplier.java:44)
		at io.cucumber.core.runtime.SingletonRunnerSupplier.get(SingletonRunnerSupplier.java:35)
		at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:35)
		at io.cucumber.core.runtime.CucumberExecutionContext.getRunner(CucumberExecutionContext.java:133)
		at io.cucumber.core.runtime.CucumberExecutionContext.runBeforeAllHooks(CucumberExecutionContext.java:86)
		at io.cucumber.core.runtime.Runtime.lambda$run$0(Runtime.java:81)
		at io.cucumber.core.runtime.Runtime.execute(Runtime.java:94)
		at io.cucumber.core.runtime.Runtime.run(Runtime.java:80)
		... 2 more
	Suppressed: io.cucumber.core.backend.CucumberBackendException: Glue class class com.mycompany.myapp.cucumber.CucumberConfiguration and class tech.jhipster.lite.cucumber.CucumberConfiguration are both annotated with @CucumberContextConfiguration.
Please ensure only one class configures the spring context

By default Cucumber scans the entire classpath for context configuration.
You can restrict this by configuring the glue path.
Examples:
 - @CucumberOptions(glue = "com.example.application")
 - @ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.example.application") - src/test/resources/junit-platform.properties   cucumber.glue=com.example.application
 - src/test/resources/cucumber.properties         cucumber.glue=com.example.application

		at io.cucumber.spring.SpringFactory.checkOnlyOneClassHasCucumberContextConfiguration(SpringFactory.java:91)
		at io.cucumber.spring.SpringFactory.addClass(SpringFactory.java:64)
		at io.cucumber.java.JavaBackend.lambda$loadGlue$1(JavaBackend.java:42)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:67)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:58)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:33)
		at io.cucumber.java.JavaBackend.lambda$loadGlue$2(JavaBackend.java:41)
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
		at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174)
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
		at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
		at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
		at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
		at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
		at io.cucumber.java.JavaBackend.loadGlue(JavaBackend.java:41)
		at io.cucumber.core.runner.Runner.<init>(Runner.java:56)
		at io.cucumber.core.runtime.SingletonRunnerSupplier.createRunner(SingletonRunnerSupplier.java:44)
		at io.cucumber.core.runtime.SingletonRunnerSupplier.get(SingletonRunnerSupplier.java:35)
		at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:35)
		at io.cucumber.core.runtime.CucumberExecutionContext.getRunner(CucumberExecutionContext.java:133)
		at io.cucumber.core.runtime.CucumberExecutionContext.runAfterAllHooks(CucumberExecutionContext.java:91)
		at io.cucumber.core.runtime.Runtime.execute(Runtime.java:94)
		at io.cucumber.core.runtime.Runtime.run(Runtime.java:84)
		... 2 more

```

**Comment by DamnClin** [comment]
Hum no, it should not... can you send the .jhipster history file?

**Comment by avdev4j** [comment]
It's available here https://github.com/avdev4j/entando-jhipster-lite/blob/main/.jhipster/modules/history.json

Tell me if I can help.

**Comment by DamnClin** [comment]
Hum, clone and launched CucumberTest, test is green

**Comment by DamnClin** [comment]
The generated cucumber report 

![entandoCucumberReport](https://user-images.githubusercontent.com/59929679/198110319-8bafcf71-c4e7-4470-8189-081bd48cec6d.png)

**Comment by pascalgrimaud** [comment]
@avdev4j : it works for me too
