### ISSUE TITLE
custom-jhlite build failed

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#4351]
See https://github.com/jhipster/jhipster-lite/pull/4317

Probably related to the upgrade to Spring Boot 3 for the engine

It couldn't be detect because the jhlite custom build use a release version, instead of a snapshot one

**Comment by DamnClin** [comment]
How does it fail? Any stack trace/way to reproduce?

**Comment by beatfreaker** [comment]
I see the below stack trace in build logs

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springdoc.webmvc.ui.SwaggerWelcomeWebMvc]: Factory method 'swaggerWelcome' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/http/HttpStatusCode
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 72 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/http/HttpStatusCode
	at org.springdoc.webmvc.ui.SwaggerConfig.swaggerWelcome(SwaggerConfig.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 73 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.http.HttpStatusCode
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 79 common frames omitted
```

**Comment by DamnClin** [comment]
Just did that on main

```
{
  "actions" : [ {
    "module" : "init",
    "date" : "2022-11-10T13:44:44.109637604Z",
    "properties" : {
      "packageName" : "com.mycompany.myapp",
      "projectName" : "JHipster Sample Application",
      "baseName" : "jhipsterSampleApplication",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "maven-java",
    "date" : "2022-11-10T13:44:44.332285499Z",
    "properties" : {
      "packageName" : "com.mycompany.myapp",
      "projectName" : "JHipster Sample Application",
      "baseName" : "jhipsterSampleApplication",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "java-base",
    "date" : "2022-11-10T13:44:44.370130567Z",
    "properties" : {
      "packageName" : "com.mycompany.myapp",
      "projectName" : "JHipster Sample Application",
      "baseName" : "jhipsterSampleApplication",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "spring-boot",
    "date" : "2022-11-10T13:44:44.430207719Z",
    "properties" : {
      "packageName" : "com.mycompany.myapp",
      "projectName" : "JHipster Sample Application",
      "baseName" : "jhipsterSampleApplication",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  }, {
    "module" : "custom-jhlite",
    "date" : "2022-11-10T13:44:44.482430208Z",
    "properties" : {
      "packageName" : "com.mycompany.myapp",
      "projectName" : "JHipster Sample Application",
      "baseName" : "jhipsterSampleApplication",
      "serverPort" : 8080,
      "endOfLine" : "lf",
      "indentSize" : 2
    }
  } ]
}
```

and it's working. What are the steps to reproduce?

**Comment by DamnClin** [comment]
The problem comes from a version shift for spring boot.Genetated apps comes with spring-boot-starter-web 2.7.5 instead of the required 3.0.0-RC1. This is because the generated app are not in spring boot 3 for now. Not sure about the most suited fix for that:

* Split JHLite to only import module + projects + front;
* Try to exclude Spring 3 dependencies;
* Wait for spring 3 migration;
* Other

**Comment by DamnClin** [comment]
Something working:

```
<properties>
<!-- ... -->
  <spring-boot.version>3.0.0-RC1</spring-boot.version>
<!-- ... -->
</properties>

<!-- ... -->

  <repositories>
    <repository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/milestone</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>spring-snapshots</id>
      <name>Spring Snapshots</name>
      <url>https://repo.spring.io/snapshot</url>
      <releases>
        <enabled>false</enabled>
      </releases>
    </repository>
  </repositories>

<!-- Delete spring boot plugin -->
```

**Comment by DamnClin** [comment]
Considering spring boot 3 is expected "soon" (https://spring.io/blog/2022/10/20/spring-boot-3-0-0-rc1-available-now#:~:text=This%20is%20our%20first%20release,to%20release%20November%2024%2C%202022.) I think we should wait for this (as it really seems to be the best solution)
