### ISSUE TITLE
cannot find symbol

### ISSUE THREAD

**Issue by medoer** [jhipster/jhipster-lite#5772]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/20471718/227525893-da751e74-89c5-4297-b3c6-3b437d6178e8.png">

cannot find the class javax.annotation.PostConstruct after generated from jhipster-lite.

**Comment by medoer** [comment]
My local machine is running open JDK 17.

**Comment by DamnClin** [comment]
Thanks a lot for reporting this. Related to kafka module which means we have 2 problems: 

* This bug; 
* The fact that no app is generated with the kafka module...

cc @pascalgrimaud I think a bounty on this one can be a good idea. I won't be able to look at it for quite some time...

**Comment by pascalgrimaud** [comment]
it's not tested in the CI because of flaky test: https://github.com/jhipster/jhipster-lite/issues/1602

cc @fdelbrayelle as you coded all this part

**Comment by DamnClin** [comment]
> And the com.xx.xx.technical.infrastructure.secondary.cache.CacheConfiguration is an empty class, no constructor and other method, but a 'CacheConfigurationTest' class has test it.

It's not empty :) it has @EnableCaching

**Comment by medoer** [comment]
Maybe should to rename the  com.xx.xx.error.infrastructure.primary.AssertionErrorsConfiguration class's name.

Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'assertionErrorsConfiguration' for bean class [com.xx.xx.error.infrastructure.primary.AssertionErrorsConfiguration] conflicts with existing, non-compatible bean definition of same name and class [tech.jhipster.lite.error.infrastructure.primary.AssertionErrorsConfiguration]

**Comment by DamnClin** [comment]
I don't really understand how you get to that situation + I don't think this is related to the original issue :)

**Comment by medoer** [comment]
> Maybe should to rename the com.xx.xx.error.infrastructure.primary.AssertionErrorsConfiguration class's name.
> 
> Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'assertionErrorsConfiguration' for bean class [com.mycompany.xx.error.infrastructure.primary.AssertionErrorsConfiguration] conflicts with existing, non-compatible bean definition of same name and class [tech.jhipster.lite.error.infrastructure.primary.AssertionErrorsConfiguration]
and some other class has the same problem, like 
MedoAssertionErrorsHandler BeanValidationErrorsHandler and so on.

**Comment by medoer** [comment]
When attempting to start the generated project, an error occurred like this:

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.medo.demo.MedoApp]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:178)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:398)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:283)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:344)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:115)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:747)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:565)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
	at com.medo.demo.MedoApp.main(MedoApp.java:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'gitInfoConfiguration' for bean class [com.medo.demo.gitinfo.infrastructure.primary.GitInfoConfiguration] conflicts with existing, non-compatible bean definition of same name and class [tech.jhipster.lite.gitinfo.infrastructure.primary.GitInfoConfiguration]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:349)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:287)
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:128)
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:289)
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:243)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:196)
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:164)
	... 18 common frames omitted

**Comment by medoer** [comment]
> GitInfoConfiguration

same bean in package: tech.jhipster.lite:jhlite:xx

**Comment by medoer** [comment]
> Yes, perfect, can't look at it right known, I'll try to find some time tomorow to reproduce but this doesn't look related to your first issue :)

OK. Thanks for taking the time to reply! yes, it's another problem. Should I open a new issue?

**Comment by medoer** [comment]
> > Should I open a new issue?
> 
> Would be great!

OK. If there are any further issues, i will do that

**Comment by DamnClin** [comment]
Ok, rebuild your app without custom-jhlite wich is a really peculiar module generating a jhipster lite instance for your organisation, not supposed to work with many other modules :)
