### ISSUE TITLE
Reduce output log in generated projects

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#584]
When launching tests in a generated projects, there are still a lot of useless logs
It means we should add more logger name to ignore in `logback.xml`

**Comment by MSaguer** [comment]
I can work in this

**Comment by pascalgrimaud** [comment]
Thanks @MSaguer 
If possible, small PR in each contexts would be cool :-)

**Comment by MSaguer** [comment]
@pascalgrimaud, I'm struggling with the traces generated by LogstashTcpLifeCycleTest unit test.
```
22:24:02,504 |-WARN in net.logstash.logback.appender.LogstashTcpSocketAppender[ASYNC_LOGSTASH_TCP] - Log destination localhost/127.0.0.1:5000: connection failed. java.net.ConnectException: Connection refused: no further information
	at java.net.ConnectException: Connection refused: no further information
	at 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
Net.java:672
	at 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
NioSocketImpl.java:542
	at 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
NioSocketImpl.java:597
	at 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
SocksSocketImpl.java:327
	at 	at java.base/java.net.Socket.connect(Socket.java:633)
Socket.java:633
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.openSocket(AbstractLogstashTcpSocketAppender.java:762)
AbstractLogstashTcpSocketAppender.java:762
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.onStart(AbstractLogstashTcpSocketAppender.java:681)
AbstractLogstashTcpSocketAppender.java:681
	at 	at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onStart(AsyncDisruptorAppender.java:382)
AsyncDisruptorAppender.java:382
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.notifyStart(BatchEventProcessor.java:224)
BatchEventProcessor.java:224
	at 	at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:120)
BatchEventProcessor.java:120
	at 	at java.base/java.lang.Thread.run(Thread.java:833)
Thread.java:833
```

I first though that it could be solved by setting logback configuration on 'net.logstash.logback' but it has no effect.
Any idea?

**Comment by pascalgrimaud** [comment]
I'll have a look

**Comment by pascalgrimaud** [comment]
I tried and I didn't find the good configuration to ignore these logs.
I think it's because of `LogstashTcpLifeCycle` which uses internal logger to send logs to Logstash.
So we can simply ignore these logs for now:
- it's during tests
- logstash is not used a lot I think, as least not at the beginning of project

Another solution would be to try to completely rework the `LogstashTcpLifeCycleTest` test, to transform to IntegrationTest, with Spring Context, but it's not deserved to spend too much time to reduce few lines of logs

**Comment by pascalgrimaud** [comment]
Following your other comment @MSaguer, I think there are some work before closing this ticket:

![image](https://user-images.githubusercontent.com/9156882/156914923-0cb386c4-34fa-4e3f-96d2-499fd78be690.png)

![image](https://user-images.githubusercontent.com/9156882/156914892-3611ffc2-b3dc-481c-93a3-4dce6082a566.png)

**Comment by MSaguer** [comment]
Unit tests seems OK for me but Integration Tests are not.
It requires new needle in application-test.properties to be able to configure logging. It's in progress.

**Comment by pascalgrimaud** [comment]
I think we already have a good approach and lot of work has been done
so this ticket can be closed

Plz claim the bounty @MSaguer

**Comment by MSaguer** [comment]
Hi @pascalgrimaud, here is the bounty claim https://opencollective.com/generator-jhipster/expenses/89915
With some delay :)

**Comment by DanielFran** [comment]
@MSaguer approved
