### ISSUE TITLE
UserJpaRepository: add missing integration test

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#619]
Add Integration Tests for [UserJpaRepository](https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/server/springboot/user/sqldatabase/UserJpaRepository.java.mustache)

- clean a little bit the [unused variables](https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/generator/server/springboot/user/sqldatabase/UserJpaRepository.java.mustache#L17-L19)
- add tests for each methods

**Comment by beatfreaker** [comment]
@pascalgrimaud `UserJpaRepository` is added by `/postgres` or `/mysql` resource/api,
now to write integration test we need some datasource, for test we can use `h2databse`
but we are adding its dependency when `/liquibase` or `/flyway` api is called
so while writing `UserJpaRepositoryIT` can we assume that `h2databse` dependency will be available ? means user will first invoke `/liquibase` and then `/mysql` ?

**Comment by pascalgrimaud** [comment]
We can assume there is already liquibase (or flyway), to create the table User
So you don't need to worry about that.
To be more precise, h2 is added with liquibase to test sync/async, not for real integration tests which are with PostgreSQL or MySQL + testcontainers instead

**Comment by beatfreaker** [comment]
okay, so for this integration test we want to use testcontainer + MySQL docker container, or we can use in-memory db i.e. h2 ?

**Comment by pascalgrimaud** [comment]
Sorry, my ticket is not clear enough :-)

The context for Integration Tests is already here, and well configured, it means you don't need to worry about that.

What is missing here is simply `UserJpaRepositoryIT.java`
It should:
- be annotated with `@IntegrationTest`
- test each requests in UserJpaRepository

Don't hesitate to tell me, if I'm not clear enough and I can show you some examples

**Comment by beatfreaker** [comment]
@pascalgrimaud I think there is some issue whith how `liquibase` scripts are generated.

After generating the project if I try to save `UserEntity` I am getting this error
```
2022-02-02 19:57:06.663  WARN 25252 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1364, SQLState: HY000
2022-02-02 19:57:06.664 ERROR 25252 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : Field 'id' doesn't have a default value
```
I fixed it by adding `autoIncrement="true"` while creating `id` column of `jhi_user` table in `liquibase`

after that if I try to save `UserEntity` I am getting this error
```
2022-02-02 20:02:43.073  WARN 25620 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1452, SQLState: 23000
2022-02-02 20:02:43.075 ERROR 25620 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : Cannot add or update a child row: a foreign key constraint fails (`test`.`jhi_user_authority`, CONSTRAINT `fk_authority_name` FOREIGN KEY (`authority_name`) REFERENCES `jhi_authority` (`name`))
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 64.545 s <<< FAILURE! - in tech.jhipster.beer.user.infrastructure.secondary.mysql.UserJpaRepositoryIT
[ERROR] tech.jhipster.beer.user.infrastructure.secondary.mysql.UserJpaRepositoryIT  Time elapsed: 64.545 s  <<< ERROR!
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
        at tech.jhipster.beer.user.infrastructure.secondary.mysql.UserJpaRepositoryIT.createUser(UserJpaRepositoryIT.java:30)
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
        at tech.jhipster.beer.user.infrastructure.secondary.mysql.UserJpaRepositoryIT.createUser(UserJpaRepositoryIT.java:30)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`test`.`jhi_user_authority`, CONSTRAINT `fk_authority_name` FOREIGN KEY (`authority_name`) REFERENCES `jhi_authority` (`name`))
        at tech.jhipster.beer.user.infrastructure.secondary.mysql.UserJpaRepositoryIT.createUser(UserJpaRepositoryIT.java:30)
```

This is the object which I am trying to save
```java
private UserEntity userEntityWithFluentSetters() {
        UserEntity userEntity = new UserEntity()
                .activated(true)
                .activationKey(ACTIVATION_KEY)
                .authorities(Set.of(new AuthorityEntity().name("myAuthority")))
                .email(EMAIL)
                .firstName("myFirstName")
                .lastName("myLastName")
                .imageUrl("myImageUrl")
                .langKey("fr")
                .login(LOGIN)
                .password("C&At!Ev4&Y7&-CvuGWnyqpmEk*3_w28%7%&df$uFQXTjqzEEwM-v34XW!na6")
                .resetDate(Instant.parse("2022-01-24T10:11:12.000Z"))
                .resetKey(RESET_KEY);

        userEntity
                .lastModifiedBy("modifier")
                .lastModifiedDate(Instant.parse("2022-01-23T10:11:12.000Z"))
                .createdBy("creator")
                .createdDate(Instant.parse("2022-01-22T10:11:12.000Z"));

        return userEntity;
    }
```

**Comment by pascalgrimaud** [comment]
Just had a look and you're right, we need `autoIncrement="true"` for MySQL only

See this line: https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs#L43

So finally, I was wrong when refactoring this: we should not have a single common user.xml for PostgreSQL / MySQL.
We should have 2 different files
This change can be done in another PR, I can take care of it.

In the meantime, you should test with PostgreSQL which is the main / default database

**Comment by pascalgrimaud** [comment]
That's why this ticket is important, to find these kind of bugs :)

Can you try to update this part for PostgreSQL, in your sample project ?

```java
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sequenceGenerator") // <--- I think it's incorrect
  @SequenceGenerator(name = "sequence_jhi_user")
  private Long id;
```

**Comment by beatfreaker** [comment]
Sure, let me try that

**Comment by beatfreaker** [comment]
Got this
```
2022-02-02 20:54:56.903  WARN 12540 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 23503
2022-02-02 20:54:56.904 ERROR 12540 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: insert or update on table "jhi_user_authority" violates foreign key constraint "fk_authority_name"
  Detail: Key (authority_name)=(myAuthority) is not present in table "jhi_authority".
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 37.194 s <<< FAILURE! - in tech.jhipster.beer.user.infrastructure.secondary.postgresql.UserJpaRepositoryIT
[ERROR] tech.jhipster.beer.user.infrastructure.secondary.postgresql.UserJpaRepositoryIT  Time elapsed: 37.194 s  <<< ERROR!
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [fk_authority_name]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
        at tech.jhipster.beer.user.infrastructure.secondary.postgresql.UserJpaRepositoryIT.createUser(UserJpaRepositoryIT.java:30)
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
        at tech.jhipster.beer.user.infrastructure.secondary.postgresql.UserJpaRepositoryIT.createUser(UserJpaRepositoryIT.java:30)
Caused by: org.postgresql.util.PSQLException:
ERROR: insert or update on table "jhi_user_authority" violates foreign key constraint "fk_authority_name"
  Detail: Key (authority_name)=(myAuthority) is not present in table "jhi_authority".
        at tech.jhipster.beer.user.infrastructure.secondary.postgresql.UserJpaRepositoryIT.createUser(UserJpaRepositoryIT.java:30)
```

Seems either something is wrong with this
```java
  @JsonIgnore
  @ManyToMany
  @JoinTable(
    name = "jhi_user_authority",
    joinColumns = { @JoinColumn(name = "user_id", referencedColumnName = "id") },
    inverseJoinColumns = { @JoinColumn(name = "authority_name", referencedColumnName = "name") }
  )
  @BatchSize(size = 20)
  private Set<AuthorityEntity> authorities = new HashSet<>();
```
or may be this
```xml
<addForeignKeyConstraint
      baseColumnNames="authority_name"
      baseTableName="jhi_user_authority"
      constraintName="fk_authority_name"
      referencedColumnNames="name"
      referencedTableName="jhi_authority"
    />
```
debuggin will, will update whatever I'll find

**Comment by pascalgrimaud** [comment]
I play a little bit with PostgreSQL and these tests work fine for me:

![image](https://user-images.githubusercontent.com/9156882/152187402-58d8f3a5-5bef-44c8-a691-63879942ca24.png)

**Comment by beatfreaker** [comment]
`repo.find` works, but `repo.save` don't
In my integration test first I am trying to generate some data, but saving new entity
and then testing the repository by calling `repo.find` methods, but `repo.save` method is throwing the exception which I mentioned in my previous comment.

**Comment by pascalgrimaud** [comment]
In my screen, I manage to save a User without changing the default ManyToMany relationship
Don't hesitate to post your complete integration tests, so I can help

**Comment by beatfreaker** [comment]
This is how my `UserJpaRepositoryIT` looks like

```java
package tech.jhipster.beer.user.infrastructure.secondary.postgresql;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.Instant;
import java.util.Set;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Pageable;
import tech.jhipster.beer.IntegrationTest;

@IntegrationTest
@TestInstance(Lifecycle.PER_CLASS)
public class UserJpaRepositoryIT {

  private static final String ACTIVATION_KEY = "my_activation_key";
  private static final String RESET_KEY = "RE1";
  private static final String LOGIN = "testuser";
  private static final String EMAIL = LOGIN + "@localhost";

  @Autowired
  UserJpaRepository userJpaRepository;

  @BeforeAll
  void createUsers() {
    userJpaRepository.save(userEntityWithFluentSetters());
  }

  @Test
  void shouldFindOneByActivationKey() {
    assertTrue(userJpaRepository.findOneByActivationKey(ACTIVATION_KEY).isPresent());
  }

  @Test
  void shouldFindAllByActivatedIsFalseAndActivationKeyIsNotNullAndCreatedDateBefore() {
    assertThat(
      userJpaRepository.findAllByActivatedIsFalseAndActivationKeyIsNotNullAndCreatedDateBefore(Instant.parse("2022-02-22T10:11:12.000Z"))
    )
      .isNotEmpty();
  }

  @Test
  void shouldFindOneByResetKey() {
    assertTrue(userJpaRepository.findOneByResetKey(RESET_KEY).isPresent());
  }

  @Test
  void shouldFindOneByEmailIgnoreCase() {
    assertTrue(userJpaRepository.findOneByEmailIgnoreCase(EMAIL).isPresent());
  }

  @Test
  void shouldFindOneByLogin() {
    assertTrue(userJpaRepository.findOneByLogin(LOGIN).isPresent());
  }

  @Test
  void shouldFindOneWithAuthoritiesByLogin() {
    assertTrue(userJpaRepository.findOneWithAuthoritiesByLogin(LOGIN).isPresent());
  }

  @Test
  void shouldFindOneWithAuthoritiesByEmailIgnoreCase() {
    assertTrue(userJpaRepository.findOneWithAuthoritiesByEmailIgnoreCase(EMAIL).isPresent());
  }

  @Test
  void shouldFindAllByIdNotNullAndActivatedIsTrue() {
    assertThat(userJpaRepository.findAllByIdNotNullAndActivatedIsTrue(Pageable.ofSize(10)).getTotalElements()).isGreaterThanOrEqualTo(1);
  }

  private UserEntity userEntityWithFluentSetters() {
    UserEntity userEntity = new UserEntity()
      .activated(false)
      .activationKey(ACTIVATION_KEY)
      .authorities(Set.of(new AuthorityEntity().name("myAuthority")))
      .email(EMAIL)
      .firstName("myFirstName")
      .lastName("myLastName")
      .imageUrl("myImageUrl")
      .langKey("fr")
      .login(LOGIN)
      .password("C&At!Ev4&Y7&-CvuGWnyqpmEk*3_w28%7%&df$uFQXTjqzEEwM-v34XW!na6")
      .resetDate(Instant.parse("2022-01-24T10:11:12.000Z"))
      .resetKey(RESET_KEY);

    userEntity
      .lastModifiedBy("modifier")
      .lastModifiedDate(Instant.parse("2022-01-23T10:11:12.000Z"))
      .createdBy("creator")
      .createdDate(Instant.parse("2022-01-22T10:11:12.000Z"));

    return userEntity;
  }
}

```

**Comment by pascalgrimaud** [comment]
If you need Authority, you need to save it separately. See my Integration Test, I played with:

```java
package tech.jhipster.beer.user.infrastructure.secondary.postgresql;

import static org.assertj.core.api.Assertions.*;

import java.util.List;
import java.util.Set;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
import tech.jhipster.beer.IntegrationTest;

@IntegrationTest
class UserJpaRepositoryIT {

  @Autowired
  AuthorityJpaRepository authorityJpaRepository;

  @Autowired
  UserJpaRepository userJpaRepository;

  @Test
  void shouldFindAll() {
    List<UserEntity> result = userJpaRepository.findAll();

    assertThat(result).isNotEmpty().hasSize(2);
  }

  @Test
  @Transactional
  void shouldFindOneByLogin() {
    AuthorityEntity authorityEntity = authorityJpaRepository
      .save(new AuthorityEntity().name("ROLE_BEER"));

    UserEntity userEntity = new UserEntity()
      .login("chips")
      .email("chips@chips.com")
      .password("chipschipschipschipschipschipschipschipschipschipschipschips")
      .activated(true)
      .authorities(Set.of(authorityEntity));
    userEntity.setCreatedBy("admin");
    userJpaRepository.save(userEntity);

    UserEntity result = userJpaRepository.findOneByLogin("chips").orElse(null);

    assertThat(result).isNotNull();
    assertThat(result.getLogin()).isEqualTo("chips");
    assertThat(result.getAuthorities()).isNotEmpty();
  }
}
```

**Comment by beatfreaker** [comment]
This is interesting, will write in this way, thank you for the suggestion

**Comment by pascalgrimaud** [comment]
Thanks for helping this project :-)))
