### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by flcarre** [jhipster/jhipster-lite#723]
Hello !

I just clone the project then run ``` ./mvnw clean verify ``` and i got this error, i don't know how to reproduce this error.

```INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.502 s
[INFO] Finished at: 2022-02-14T14:02:18+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project jhlite: There are test failures.
[ERROR]
[ERROR] Please refer to /home/fcarre/ippon/jhipster/jhipster-lite/1/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/fcarre/ippon/jhipster/jhipster-lite/1 && /usr/jdk-17.0.2/bin/java '-javaagent:/home/fcarre/.m2/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/home/fcarre/ippon/jhipster/jhipster-lite/1/target/jacoco.exec,excludes=**/generator/buildtool/maven/.mvn/wrapper/*' -jar /home/fcarre/ippon/jhipster/jhipster-lite/1/target/surefire/surefirebooter7626789812364003369.jar /home/fcarre/ippon/jhipster/jhipster-lite/1/target/surefire 2022-02-14T14-02-18_514-jvmRun1 surefire15746835623112398163tmp surefire_04009655021043759652tmp
[ERROR]
[ERROR] Error while executing forked tests.Error while executing process.Cannot run program "/bin/sh" (in directory "/home/fcarre/ippon/jhipster/jhipster-lite/1"): error=13, Permission deniedorg.apache.maven.surefire.shared.utils.cli.CommandLineException: Error while executing process.
[ERROR]         at org.apache.maven.surefire.shared.utils.cli.Commandline.execute(Commandline.java:438)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.lazytestprovider.OutputStreamFlushableCommandline.execute(OutputStreamFlushableCommandline.java:88)
[ERROR]         at org.apache.maven.surefire.extensions.util.CommandlineExecutor.execute(CommandlineExecutor.java:80)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:637)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
[ERROR]         at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
[ERROR]         at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
[ERROR] Caused by: java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/fcarre/ippon/jhipster/jhipster-lite/1"): error=13, Permission denied
[ERROR]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
[ERROR]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
[ERROR]         at java.base/java.lang.Runtime.exec(Runtime.java:594)
[ERROR]         at org.apache.maven.surefire.shared.utils.cli.Commandline.execute(Commandline.java:433)
[ERROR]         ... 37 more
[ERROR] Caused by: java.io.IOException: error=13, Permission denied
[ERROR]         at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[ERROR]         at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
[ERROR]         at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
[ERROR]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
[ERROR]         ... 40 more
[ERROR] Fatal Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Flakes: 0, Elapsed timeout: false
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/fcarre/ippon/jhipster/jhipster-lite/1 && /usr/jdk-17.0.2/bin/java '-javaagent:/home/fcarre/.m2/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/home/fcarre/ippon/jhipster/jhipster-lite/1/target/jacoco.exec,excludes=**/generator/buildtool/maven/.mvn/wrapper/*' -jar /home/fcarre/ippon/jhipster/jhipster-lite/1/target/surefire/surefirebooter7626789812364003369.jar /home/fcarre/ippon/jhipster/jhipster-lite/1/target/surefire 2022-02-14T14-02-18_514-jvmRun1 surefire15746835623112398163tmp surefire_04009655021043759652tmp
[ERROR]
[ERROR] Error while executing forked tests.Error while executing process.Cannot run program "/bin/sh" (in directory "/home/fcarre/ippon/jhipster/jhipster-lite/1"): error=13, Permission deniedorg.apache.maven.surefire.shared.utils.cli.CommandLineException: Error while executing process.
[ERROR]         at org.apache.maven.surefire.shared.utils.cli.Commandline.execute(Commandline.java:438)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.lazytestprovider.OutputStreamFlushableCommandline.execute(OutputStreamFlushableCommandline.java:88)
[ERROR]         at org.apache.maven.surefire.extensions.util.CommandlineExecutor.execute(CommandlineExecutor.java:80)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:637)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
[ERROR]         at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
[ERROR]         at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
[ERROR] Caused by: java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/fcarre/ippon/jhipster/jhipster-lite/1"): error=13, Permission denied
[ERROR]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
[ERROR]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
[ERROR]         at java.base/java.lang.Runtime.exec(Runtime.java:594)
[ERROR]         at org.apache.maven.surefire.shared.utils.cli.Commandline.execute(Commandline.java:433)
[ERROR]         ... 37 more
[ERROR] Caused by: java.io.IOException: error=13, Permission denied
[ERROR]         at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[ERROR]         at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
[ERROR]         at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
[ERROR]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
[ERROR]         ... 40 more
[ERROR] Fatal Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Flakes: 0, Elapsed timeout: false
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:748)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:305)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:265)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
[ERROR]         at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
[ERROR]         at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
[ERROR] Caused by: java.io.IOException: Cannot run program "/bin/sh" (in directory "/home/fcarre/ippon/jhipster/jhipster-lite/1"): error=13, Permission denied
[ERROR]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
[ERROR]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
[ERROR]         at java.base/java.lang.Runtime.exec(Runtime.java:594)
[ERROR]         at org.apache.maven.surefire.shared.utils.cli.Commandline.execute(Commandline.java:433)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.lazytestprovider.OutputStreamFlushableCommandline.execute(OutputStreamFlushableCommandline.java:88)
[ERROR]         at org.apache.maven.surefire.extensions.util.CommandlineExecutor.execute(CommandlineExecutor.java:80)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:637)
[ERROR]         ... 34 more
[ERROR] Caused by: java.io.IOException: error=13, Permission denied
[ERROR]         at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
[ERROR]         at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
[ERROR]         at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
[ERROR]         at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
[ERROR]         ... 40 more
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Complete stack trace:

[message.txt](https://github.com/jhipster/jhipster-lite/files/8067522/message.txt)

**Comment by pascalgrimaud** [comment]
We check together, and some additional information:
- you use Windows wsl ubuntu
- the java --version and javac --version are correctly Java 17
- permissions are ok for projects and /tmp

**Comment by pascalgrimaud** [comment]
Opened for so long so let's close this ticket as we didn't manage to reproduce it in another machine
