### ISSUE TITLE
Cannot generate a projet - Modules not applied

### ISSUE THREAD

**Issue by thejavator** [jhipster/jhipster-lite#9861]
Hello,

 

Since two or three days, I cannot generate a project.

This happens even with two or three modules (at the stage of java).

 

I've got a visual error  : 'Modules not applied'

 

When checking network call, I see a server error :

```

{

    "timestamp": "2024-05-21T14:19:00.207+00:00",

    "status": 500,

    "error": "Internal Server Error",

    "path": "/api/apply-patches"

}


```

Have you noticed any of this kind of error ?

**Comment by renanfranca** [comment]
Hello @thejavator,

Could you please share the `.jhipster/modules/history.json` file? It should be located in the project folder.

Thank you :)

**Comment by renanfranca** [comment]
> web interface lite.jhipster.tech

Could you share a screenshot of the selected modules in landscape mode?

Please try to reproduce the problem by selecting as few modules as possible.

Thanks ✌️

**Comment by thejavator** [comment]
This a screenshot using my phone but I've got  the same using desktop. 
I've selected maven-java. 
![Screenshot_20240521_182741_Chrome](https://github.com/jhipster/jhipster-lite/assets/6198887/d083b872-dd0d-4418-9eb6-fd7b108ac66b)

**Comment by pascalgrimaud** [comment]
I confirm the issue.
The cloud version is managed by @jdubois 
Can you have a look plz?

**Comment by jdubois** [comment]
Yes I’ll have a look today!

**Comment by jdubois** [comment]
Weird, here's the log for reference:

```
2024-05-22T06:10:13.486150801Z 2024-05-22T06:10:13.485Z ERROR 1 --- [jhlite] [-handler-125390] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.IllegalArgumentException: Enumerated values of type org.eclipse.jgit.lib.CoreConfig$TrustLooseRefStat not available] with root cause
2024-05-22T06:10:13.486180781Z 
2024-05-22T06:10:13.486187101Z java.lang.NoSuchMethodException: org.eclipse.jgit.lib.CoreConfig$TrustLooseRefStat.values()
2024-05-22T06:10:13.486191697Z  at java.base@21.0.2/java.lang.Class.checkMethod(DynamicHub.java:1075)
2024-05-22T06:10:13.486195607Z  at java.base@21.0.2/java.lang.Class.getMethod(DynamicHub.java:1060)
2024-05-22T06:10:13.486200168Z  at org.eclipse.jgit.lib.Config.allValuesOf(Config.java:425)
2024-05-22T06:10:13.486204758Z  at org.eclipse.jgit.lib.Config.getEnum(Config.java:417)
2024-05-22T06:10:13.486208473Z  at org.eclipse.jgit.internal.storage.file.RefDirectory.<init>(RefDirectory.java:222)
2024-05-22T06:10:13.486226122Z  at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(FileRepository.java:189)
2024-05-22T06:10:13.486229459Z  at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:627)
2024-05-22T06:10:13.486232850Z  at org.eclipse.jgit.api.InitCommand.call(InitCommand.java:101)
2024-05-22T06:10:13.486236878Z  at tech.jhipster.lite.module.infrastructure.secondary.git.JGitGitRepository.init(JGitGitRepository.java:33)
2024-05-22T06:10:13.486240073Z  at java.base@21.0.2/java.lang.reflect.Method.invoke(Method.java:580)
```

This is currently running version v1.6.0, I'm upgrading to the latest (v1.8.0) release.

**Comment by jdubois** [comment]
Upgrading to v1.8.0 didn't solve the issue.

**Comment by pascalgrimaud** [comment]
Do you use the default Docker image or a native one?

**Comment by jdubois** [comment]
@pascalgrimaud I'm using the native image:
`jhipster/jhipster-lite-native:v1.8.0`

Can you try on your Linux machine? As I have a Mac, I can't execute it locally.

**Comment by jdubois** [comment]
I'm guessing it's a GraalVM issue with JGit

**Comment by pascalgrimaud** [comment]
> I'm guessing it's a GraalVM issue with JGit

I'm sure it is :-D

**Comment by pascalgrimaud** [comment]
Using locally the command `docker run -p 7471:7471 --rm jhipster/jhipster-lite-native:v1.8.0`, I confirm the issue:

![image](https://github.com/jhipster/jhipster-lite/assets/9156882/041320c8-8cd2-4744-ba39-ce92cd29b2d0)

**Comment by pascalgrimaud** [comment]
I think we need to improve this class https://github.com/jhipster/jhipster-lite/blob/main/src/main/java/tech/jhipster/lite/module/infrastructure/primary/NativeHints.java

**Comment by atomfrede** [comment]
I will have a look

**Comment by atomfrede** [comment]
Seems pretty straight forward, the quarkus config has done it already (https://github.com/quarkiverse/quarkus-jgit/blob/main/deployment/src/main/java/io/quarkus/jgit/deployment/JGitProcessor.java). Will do some local testing with native docker image and native binary and do the PR afterwards.

**Comment by pascalgrimaud** [comment]
@murdos : do you want me to do a release ?

**Comment by murdos** [comment]
@pascalgrimaud : yes, it would be great, since it's currently blocking usage of https://lite.jhipster.tech

@jdubois : do you think you could allow @pascalgrimaud and me to update https://lite.jhipster.tech, in order to always use the last version?

**Comment by jdubois** [comment]
Unfortunately not, as I have a specific employee account, I can't share it with you (there's a security risk, and you could see some non-released stuff...).
We'd need to migrate to GCP for this, what do you think about it?

**Comment by murdos** [comment]
@jdubois : yeah, I think it would be nice if multiple people could be in charge of updating and maintaining lite.jhipster.tech.
If that implies moving to GCP it's fine for me.
@pascalgrimaud : WDYT?

**Comment by pascalgrimaud** [comment]
It is a good idea to migrate to GCP, but I don't know who can help. Maybe @PierreBesson or @SudharakaP ?
